version: "3.7"
#
# to build, run: docker compose -f docker-compose.build.yml build
# or if testing-harness was modified, you must use this:
#  docker compose -f docker-compose.build.yml build --no-cache
#
services:
  perfsonar:
    image: bltierney/perfsonar-testpoint-bbrv3-testing:latest
    build:
      context: .
      dockerfile: Dockerfile
